### PR TITLE
Remove CLI scripts

### LINKED ISSUE #3: Remove CLI scripts
Remove the /cli script folder. 

_Rationale_ : Functionality doesn't belong in the core. Developers that need a CLI can use [Joomlatools Console](https://github.com/joomlatools/joomlatools-console)

### PR DESCRIPTION
**Pull request by koobitor**
resolve #3

### CODE REVIEW

**Comment by johanjanssens** [comment]
@koobitor Thanks for working on this. A little bit of guidance, every issue should be done through a seperate PR, do not commit multiple issues in the same PR. Can you please update this PR and revert the work you did on removing the help and move that into a new PR please. Thanks!

**Comment by johanjanssens** [comment]
@koobitor There is no reason to close this PR, you just need to update your fork on your end and revert the changes you did to #1 

The best way to do that is to remove the commit with hash 36f5f4f, if that's the last commit you did a simple git reset HEAD will do and then do a "force push". 

More info: 

- http://www.clock.co.uk/blog/deleting-a-git-commit
- https://githowto.com/removing_commits_from_a_branch
- https://ariejan.net/2011/09/08/git-remove-reset-and-rollback-commits/

**Comment by koobitor** [comment]
@johanjanssens i already fix it. Thank for your suggest. :)

**Comment by johanjanssens** [comment]
@koobitor Excellent work! Thanks!

**Comment by johanjanssens** [comment]
@koobitor With this one merged, you can now submit a new PR for the removal of the help. Make sure that it only includes the commit to remove help and not this commit for the CLI anymore.

**Pull request merged**
