### PR TITLE
Remove help

### LINKED ISSUE #1: Remove help
See: https://github.com/joomlatools/joomlatools-platform/pull/35

_Rationale_: goal is to make the distro easily re-brandable. The help system is directly tied to the Joomla.org resources.

### PR DESCRIPTION
**Pull request by koobitor**
resolve #1

### CODE REVIEW

**Comment by johanjanssens** [comment]
@koobitor This PR has conflicts and cannot be merged, can you please check the conflicts and fix them? If you need help please let me know.

**Comment by koobitor** [comment]
I will create new pr again form another branch. @johanjanssens

**Comment by johanjanssens** [comment]
@koobitor No need to create a new PR, just update this PR and update your local branch. Can you do that?

**Comment by johanjanssens** [comment]
@koobitor Can you give me access to your forked repo, I will fix the conflict for you and then this one can be merged.

**Comment by koobitor** [comment]
@johanjanssens can i try to solve it again.
I test on https://github.com/koobitor/joomla-spark/commits/feature/1-removehelp it already work.
I will do it again in this branch.

**Comment by koobitor** [comment]
@johanjanssens i already fix this branch.

**Comment by johanjanssens** [comment]
Great! Good work.

**Pull request merged**
