### PR TITLE
Upgrade to 3.6.2

### LINKED ISSUE #80: Upgrade to Joomla 3.6.2
References:

- https://github.com/joomla/joomla-cms/compare/3.6.0...3.6.2 
- https://github.com/joomla/joomla-cms/commits/3.6.2

### PR DESCRIPTION
**Pull request by johanjanssens**
resolve #80

### CODE REVIEW

**Comment by johanjanssens** [comment]
@joomlacorner @imarklee Can you guys test this and see if everything is working?

**Comment by joomlacorner** [comment]
@johanjanssens  I compared all files with Joomla 3.6.2 Full package.
look like it's missing some new files. Can you help to recheck it?

example in com_admin  
screen shot 2559-08-24 at 1 09 33 pm

**Comment by johanjanssens** [comment]
@joomlacorner Yes, since we removed help and some other things the files will not be the same. This normal. It was quite hard to merge things so there could be still something wrong.

**Comment by joomlacorner** [comment]
@johanjanssens  about the problem on installation loop in this package. it's need to fixed on this update. or we will create with other issue to fixed it. I found what's files to fixed it.

**Comment by johanjanssens** [comment]
@joomlacorner Can be both, the easiest would be if you create a PR to fix this against the feature/80-upgrade branch, that PR will then update this one once merged. Does that make sense?

**Comment by joomlacorner** [comment]
@imarklee I have fixed installation loop. Can you help to review this PR?

**Comment by johanjanssens** [comment]
@joomlacorner Strange that I missed all these files when I upgraded, what process did you use to do the merge, also are you sure everything has now been merged? If not we might need to double check?

**Comment by joomlacorner** [comment]
@johanjanssens   my step is.
1. I'm checkout this Branch feature/80-upgrade and compare all files with Joomla 3.6.2 Full package also remember what's we have removed it. I used Araxis Merge to compared it. 
2. after recheck and finish it. I checkout and tested to install this package. it's worked.
3. commit to this branch.

**Comment by johanjanssens** [comment]
@joomlacorner It seems that the changes you have pushed to the branch have created conflicts which prevent me to merge it ? Can you look into that?

**Pull request merged**
